#!/bin/bash
cd $(dirname $(readlink -f "$0") )
capps=()
cthemes=()
ffamilies=""
localonly=""
nvimin=""
p10kc=""
picomc=""
psed=""
qgset=""
terml=""
viml="/etc/vimrc"
xcont=""
xprofin=""
zshc="/etc/zsh/zshrc"
zshs=""

setenv () {
	if [ "$localonly" != "" ]; then
		echo "export $1" >> "$HOME/.profile"
	else
		echo "$1" | sudo tee -a /etc/environment >/dev/null
	fi
}
zshcadd () {
	if [ "$localonly" != "" ]; then
		tee $1 "$HOME/.zshrc" >/dev/null
	else
		sudo tee $1 "$zshc" >/dev/null
	fi
}

while [ "$1" != "" ]; do
	case "$1" in 
		-c) # add folder to copy to .config
			capps+=("$2")
			shift
			;;
		-ct) # add theme to copy
			cthemes+=("$2")
			shift
			;;
		-f) # set custom name for fontconfig families file
			ffamilies="$2"
			shift
			;;
		-l) # preferably install config files locally
			localonly="yes"
			;;
		-n) # use neovim instead of vim
			nvimin="yes"
			;;
		-p) # use p10k in zsh
			p10kc="yes"
			;;
		-pc) # copy picom config
			picomc="yes"
			;;
		-pi) # install p10k
			p10kc="install"
			;;
		-ps) # sed on polkit nopasswd file
			psed="$2"
			shift
			;;
		-qg) # set gtk2 qt style
			qgset="QT_QPA_PLATFORMTHEME=gtk2"
			;;
		-qk) # set kvantum qt style
			qgset="QT_STYLE_OVERRIDE=kvantum"
			;;
		-t) # set TERMINAL
			terml="$2"
			shift
			;;
		-v) # location of vimrc
			viml="$2"
			shift
			;;
		-xc) # copy game controller udev rule
			xcont="yes"
			;;
		-xp) # copy xprofile file
		   	xprofin="#"
			;;
		-xs) # sed on xprofile
			xprofin="$2"
			shift
			;;
		-z) # location of zshrc (full path + filename 'zshrc')
			zshc="$2"
			shift
			;;
		-zs) # sed on zshrc
			zshs="$2"
			shift
			;;
	esac
	shift
done

sudo usermod -a -G video $(whoami)

sudo usermod -s /bin/zsh $(whoami)
sudo usermod -s /bin/zsh root

mkdir "$HOME/.config"
mkdir "$HOME/.themes"
if [ "$p10kc" = "install" ]; then
	sudo git clone --depth=1 https://github.com/romkatv/powerlevel10k.git /usr/share/zsh-theme-powerlevel10k
fi
if [ "$p10kc" != "" ]; then
	cp p10k.zsh ~/.p10k.zsh
	echo '
	# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
	# Initialization code that may require console input (password prompts, [y/n]
	# confirmations, etc.) must go above this block; everything else may go below.
	if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
	  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
	fi' | zshcadd
fi
sed "$zshs" zshrc | zshcadd -a
touch ~/.zshrc
if [ "$p10kc" != "" ]; then
	zshcadd -a <<'EOL'
	source /usr/share/zsh-theme-powerlevel10k/powerlevel10k.zsh-theme
	# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
	[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh
EOL
fi
echo 'export GOPATH=~/Public/go' >> ~/.profile
chmod +x ~/.profile
if [ "$qgset" != "" ]; then
	setenv "$qgset"
fi
if [ "$terml" != "" ]; then
	setenv "TERMINAL=$terml"
fi
git config --global user.name "Popa Ioan Alexandru"
git config --global user.email "alexioanpopa11@gmail.com"

if [ "$localonly" != "" ]; then
	install -Dm644 vimrc "$HOME/.vimrc"
	mkdir "$HOME/.fonts"
	cp -r iosevka-custom "$HOME/.fonts"
	install -Dm644 50-families.conf "$HOME/.config/fontconfig/conf.d/$ffamilies"
else
	cat vimrc | sudo tee -a "$viml" >/dev/null
	sudo cp -r iosevka-custom /usr/share/fonts
	sudo install -Dm644 50-families.conf "/etc/fonts/conf.d/$ffamilies"
fi
sudo install -Dm644 00-keyboard.conf /etc/X11/xorg.conf.d/00-keyboard.conf
sudo install -Dm644 30-touchpad.conf /etc/X11/xorg.conf.d/30-touchpad.conf

if [ "$xcont" != "" ]; then
	sudo cp 51-xbox-gamepad.rules /etc/udev/rules.d/
fi
sudo mkdir -p /etc/polkit-1/rules.d/
if [ "$psed" != "" ]; then
	sed "$psed" 49-nopasswd_global.rules | sudo tee /etc/polkit-1/rules.d/49-nopasswd_global.rules >/dev/null
else
	sudo cp 49-nopasswd_global.rules /etc/polkit-1/rules.d/
fi
if [ "$nvimin" != "" ]; then
	if [ "$localonly" != "" ]; then
		mkdir -p ~/.config/nvim/
		echo "source $HOME/.vimrc" > ~/.config/nvim/init.vim
	else
		sudo mkdir -p /etc/xdg/nvim/
		echo "source $viml" | sudo tee -a /etc/xdg/nvim/sysinit.vim >/dev/null
	fi
	echo "alias vim='nvim'" | zshcadd -a
	setenv "EDITOR=nvim"
else
	setenv "EDITOR=vim"
fi
if [ "$picomc" != "" ]; then
	if [ "$localonly" != "" ]; then
		install -Dm644 picom.conf "$HOME/.config/picom.conf"
	else
		sudo install -Dm644 picom.conf /etc/xdg/picom.conf
	fi
fi
if [ "$xprofin" != "" ]; then
	if [ "$localonly" != "" ]; then
		sed "$xprofin" xprofile > "$HOME/.xprofile"
	else
		sed "$xprofin" xprofile | sudo tee /etc/xprofile >/dev/null
	fi
fi
for capp in "${capps[@]}"; do
	cp -r "$capp" "$HOME/.config"
done
for ctheme in "${cthemes[@]}"; do
	if [ "$localonly" != "" ]; then
		cp -r "$ctheme" "$HOME/.themes"
	else
		sudo cp -r "$ctheme" "/usr/share/themes"
	fi
done
