#!/bin/bash
cd $(dirname $(readlink -f "$0") )
capps=()
cthemes=()
ffamilies=""
psed=""
nvimin=""
p10kc=""
picomc=""
qgset=""
terml=""
viml="/etc/vimrc"
xcont=""
xprofin=""
zshc="/etc/zsh/zshrc"
zshs=""

while [ "$1" != "" ]; do
	case "$1" in 
		-c) # add folder to copy to .config
			capps+=("$2")
			shift
			;;
		-ct) # add theme to copy
			cthemes+=("$2")
			shift
			;;
		-f) # set custom name for fontconfig families file
			ffamilies="$2"
			shift
			;;
		-n) # use neovim instead of vim
			nvimin="yes"
			;;
		-p) # use p10k in zsh
			p10kc="yes"
			;;
		-pc) # copy picom config
			picomc="yes"
			;;
		-pi) # install p10k
			p10kc="install"
			;;
		-ps) # sed on polkit nopasswd file
			psed="$2"
			shift
			;;
		-qg) # set gtk2 qt style
			qgset="QT_QPA_PLATFORMTHEME=gtk2"
			;;
		-qk) # set kvantum qt style
			qgset="QT_STYLE_OVERRIDE=kvantum"
			;;
		-t) # set TERMINAL
			terml="$2"
			shift
			;;
		-v) # location of vimrc
			viml="$2"
			shift
			;;
		-xc) # copy game controller udev rule
			xcont="yes"
			;;
		-xp) # copy xprofile file
		   	xprofin="#"
			;;
		-xs) # sed on xprofile
			xprofin="$2"
			shift
			;;
		-z) # location of zshrc (full path + filename 'zshrc')
			zshc="$2"
			shift
			;;
		-zs) # sed on zshrc
			zshs="$2"
			shift
			;;
	esac
	shift
done

sudo usermod -a -G video $(whoami)

sudo usermod -s /bin/zsh $(whoami)
sudo usermod -s /bin/zsh root

if [ "$p10kc" = "install" ]; then
	sudo git clone --depth=1 https://github.com/romkatv/powerlevel10k.git /usr/share/zsh-theme-powerlevel10k
fi
if [ "$p10kc" != "" ]; then
	cp p10k.zsh ~/.p10k.zsh
	echo '
	# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
	# Initialization code that may require console input (password prompts, [y/n]
	# confirmations, etc.) must go above this block; everything else may go below.
	if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
	  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
	fi' | sudo tee "$zshc" >/dev/null
fi
sed "$zshs" zshrc | sudo tee -a "$zshc" >/dev/null
cat > ~/.zshrc <<'EOL'
HISTFILE=~/.histfile
HISTSIZE=1000
SAVEHIST=1000
EOL
if [ "$p10kc" != "" ]; then
	cat >> ~/.zshrc <<'EOL'
	source /usr/share/zsh-theme-powerlevel10k/powerlevel10k.zsh-theme
	# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
	[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh
EOL
fi
echo 'export GOPATH=~/Public/go' >> ~/.profile
if [ "$qgset" != "" ]; then
	echo "$qgset" | sudo tee -a /etc/environment >/dev/null
fi
if [ "$terml" != "" ]; then
	echo "TERMINAL=$terml" | sudo tee -a /etc/environment >/dev/null
fi
git config --global user.name "Popa Ioan Alexandru"
git config --global user.email "alexioanpopa11@gmail.com"

sudo mkdir -p /etc/X11/xorg.conf.d/
sudo mkdir -p /etc/polkit-1/rules.d/
cat vimrc | sudo tee -a "$viml" >/dev/null
sudo cp -r iosevka-custom /usr/share/fonts
sudo cp 00-keyboard.conf /etc/X11/xorg.conf.d/
sudo cp 30-touchpad.conf /etc/X11/xorg.conf.d/
sudo cp 50-families.conf "/etc/fonts/conf.d/$ffamilies"

if [ "$xcont" != "" ]; then
	sudo cp 51-xbox-gamepad.rules /etc/udev/rules.d/
fi
if [ "$psed" != "" ]; then
	sed "$psed" 49-nopasswd_global.rules | sudo tee /etc/polkit-1/rules.d/49-nopasswd_global.rules >/dev/null
else
	sudo cp 49-nopasswd_global.rules /etc/polkit-1/rules.d/
fi
if [ "$nvimin" != "" ]; then
	sudo mkdir -p /etc/xdg/nvim/
	echo "source $viml"| sudo tee -a /etc/xdg/nvim/sysinit.vim >/dev/null
	echo "alias vim='nvim'" | sudo tee -a "$zshc" >/dev/null
	echo "EDITOR=nvim" | sudo tee -a /etc/environment >/dev/null
else
	echo "EDITOR=vim" | sudo tee -a /etc/environment >/dev/null
fi
if [ "$picomc" != "" ]; then
	sudo install -Dm644 picom.conf /etc/xdg/picom.conf
fi
if [ "$xprofin" != "" ]; then
	sed "$xprofin" xprofile | sudo tee /etc/xprofile >/dev/null
fi
mkdir "$HOME/.config"
for capp in "${capps[@]}"; do
	cp -r "$capp" "$HOME/.config"
done
for ctheme in "${cthemes[@]}"; do
	sudo cp -r "$ctheme" "/usr/share/themes"
done
