#!/bin/sh

numlockx on &
pamac-tray &

if [ -z "$XDG_CURRENT_DESKTOP" ] && [ "$DESKTOP_SESSION" != "cinnamon" ]; then
	xsettingsd 2>/dev/null &
	udiskie --smart-tray &
	sxhkd &
	parcellite &
	blueman-applet &
	nm-applet &
	picom &
	xss-lock env XSECURELOCK_DISCARD_FIRST_KEYPRESS=0 XSECURELOCK_SHOW_DATETIME=1 XSECURELOCK_DATETIME_FORMAT='%A, %d %b %Y, %H:%M:%S' xsecurelock &
	if [ "$DESKTOP_SESSION" != "awesome" ]; then
		/usr/lib/xfce4/notifyd/xfce4-notifyd &
	fi
	eval $(/usr/bin/gnome-keyring-daemon --start)
	export SSH_AUTH_SOCK
fi
