#!/bin/sh

numlockx on &
pamac-tray &
sxhkd &

if [ -z "$XDG_CURRENT_DESKTOP" ] && [ "$DESKTOP_SESSION" != "cinnamon" ]; then
	udiskie --smart-tray &
	parcellite &
	blueman-tray &
	nm-applet &
	picom &
	if [ "$DESKTOP_SESSION" != "awesome" ]; then
		/usr/lib/xfce4/notifyd/xfce4-notifyd &
	fi
fi
