#!/bin/sh

$HOME/.config/polybar/launch.sh nonexample &
sxhkd &

bspc config border_width          4
#bspc config bottom_padding       10
#bspc config left_padding         10
#bspc config right_padding        10
bspc config window_gap            10
bspc config split_ratio           0.50
bspc config focus_follows_pointer true
bspc config single_monocle        false
bspc config borderless_monocle    false
bspc config gapless_monocle       false

bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner

bspc config normal_border_color	  "#575b70"
bspc config active_border_color	  "#282a33"
bspc config focused_border_color  "#bd93f9"
bspc config presel_feedback_color "#ff79c6"
bspc config urgent_border_color	  "#ff5555"

bspc monitor -d 1 2 3 4 5 6 7 8 9 10
